"""user model added

Revision ID: 003ee523cfce
Revises: a56a145ebc7b
Create Date: 2021-12-13 14:26:01.248925

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = '003ee523cfce'
down_revision = 'a56a145ebc7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
