"""user 

Revision ID: 123444b934d0
Revises: 5c3ffe8f101b
Create Date: 2021-12-13 14:46:54.736137

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = '123444b934d0'
down_revision = '5c3ffe8f101b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
