"""user model add id

Revision ID: 1760d63a3ee8
Revises: 743d66382b8b
Create Date: 2021-12-13 14:34:37.458928

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = '1760d63a3ee8'
down_revision = '743d66382b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
