"""user finally added

Revision ID: 29bc60e05327
Revises: b311920d618e
Create Date: 2021-12-13 14:49:49.768628

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = '29bc60e05327'
down_revision = 'b311920d618e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
