"""query didnt work

Revision ID: 65f838bc1e58
Revises: 68d8226da012
Create Date: 2021-12-12 15:15:32.040198

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = '65f838bc1e58'
down_revision = '68d8226da012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_query_dated', table_name='query')
    op.drop_column('query', 'dated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('dated', sa.DATE(), autoincrement=False, nullable=True))
    op.create_index('ix_query_dated', 'query', ['dated'], unique=False)
    # ### end Alembic commands ###
