"""user model added1

Revision ID: 67c7f3daf1fc
Revises: 003ee523cfce
Create Date: 2021-12-13 14:26:38.750200

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = '67c7f3daf1fc'
down_revision = '003ee523cfce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
