"""dosnt work 111

Revision ID: 68d8226da012
Revises: 2f6b4fae5d00
Create Date: 2021-12-12 15:14:13.817599

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = '68d8226da012'
down_revision = '2f6b4fae5d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('test', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_url_test'), 'url', ['test'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_test'), table_name='url')
    op.drop_column('url', 'test')
    # ### end Alembic commands ###
