"""user model add sd

Revision ID: 7060ebd1cb3f
Revises: 1760d63a3ee8
Create Date: 2021-12-13 14:41:49.633409

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = '7060ebd1cb3f'
down_revision = '1760d63a3ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
