"""new init

Revision ID: 7092a224ce04
Revises: 690774a9f80c
Create Date: 2021-12-12 14:46:44.853175

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = '7092a224ce04'
down_revision = '690774a9f80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
