"""user model add

Revision ID: 743d66382b8b
Revises: 67c7f3daf1fc
Create Date: 2021-12-13 14:30:53.414554

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = '743d66382b8b'
down_revision = '67c7f3daf1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
