"""ah

Revision ID: 93fdb7a1792b
Revises: 7092a224ce04
Create Date: 2021-12-12 14:50:50.074411

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = '93fdb7a1792b'
down_revision = '7092a224ce04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
