"""dosnt work

Revision ID: 9789266b041e
Revises: d0222b74cfdc
Create Date: 2021-12-12 15:11:49.772474

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = '9789266b041e'
down_revision = 'd0222b74cfdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
