"""user model added

Revision ID: a56a145ebc7b
Revises: 9b4739fdb74a
Create Date: 2021-12-13 14:20:04.089484

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = 'a56a145ebc7b'
down_revision = '9b4739fdb74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
