"""ah

Revision ID: a912e1d73f61
Revises: 93fdb7a1792b
Create Date: 2021-12-12 15:05:47.371204

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = 'a912e1d73f61'
down_revision = '93fdb7a1792b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
