"""dem

Revision ID: b0b29fdb715e
Revises: d2831c0af60b
Create Date: 2021-12-14 05:52:57.042065

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = 'b0b29fdb715e'
down_revision = 'd2831c0af60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
