"""why

Revision ID: d0222b74cfdc
Revises: a912e1d73f61
Create Date: 2021-12-12 15:08:03.667722

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = 'd0222b74cfdc'
down_revision = 'a912e1d73f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
