"""dated from queryread deleted

Revision ID: d2831c0af60b
Revises: 29bc60e05327
Create Date: 2021-12-14 05:10:47.771747

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = 'd2831c0af60b'
down_revision = '29bc60e05327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
