"""user model add sdas

Revision ID: d7c34b9f238b
Revises: 7060ebd1cb3f
Create Date: 2021-12-13 14:44:03.395845

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = 'd7c34b9f238b'
down_revision = '7060ebd1cb3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
